name: webfeed
version: 0.2.1
description: A dart package for parsing RSS and Atom feed.
author: Wito Chandra <wito.c.91@gmail.com>
homepage: https://github.com/witochandra/webfeed
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  xml: "^3.0.0"
dev_dependencies:
  test: ^0.12.0
  http: "^0.11.3+16"
