name: webfeed_revised
version: 0.7.0
description: webfeed-revised is a dart package for parsing RSS and Atom feeds. Media, DublinCore, iTunes, Syndication namespaces are also supported.
homepage: https://github.com/Peterkrol12/webfeed-revised
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  intl: ^0.18.0
  xml: ^6.2.2
dev_dependencies:
  austerity: ^1.0.0
  http: ^0.13.5
  test: ^1.24.1
